#!/bin/sh
# posixsdm - Terminal-based display manager

# Menu to return to a TTY, back to the start of the script, or the login screen
ttyexit() {
printf "\nEntered exit prompt\n"
while true; do
printf "Do you want to return to the TTY or login menu? (T/E/L) "
read -r tel
	case $tel in
		[Tt]) printf "\nExiting to TTY shell...\n"
		exec $SHELL;;
		[Ee]) printf "\nExiting to TTY login...\n"
		exit 0;;
		[Ll]) printf "\nReturning to login screen...\n"
		sdmlogin;;
		*) printf "\nError: illegal input\n"
	esac
done
}

# Create function to directly start Wayland-based desktops
# First check if only one desktop file is found; if not, continue
# Afterwards, check for user input to search for wayland-sessions .desktop files
# If nothing is found, report user error
wrun() {
printf "\nEntered Wayland prompt\n"
wcheck=$(ls "$wses" | wc -l)
case "$wcheck" in
	1) printf "\nOnly one environment found, running\n"
	runwm=$(sed -n 's/^Exec=//p' $wses/*.desktop)
	exec dbus-launch --exit-with-session $runwm;;
	0) printf "\!!!CRITICAL ERROR!!!\n\nNo Wayland-based window manager or desktop environment found\nPress any key to go back to the start menu "
	read az
	sdmlogin
esac

while true; do
printf "\nWhat Wayland desktop environment do you want to enter?\n"
printf "\nThe following options are available:\nView .desktop files, Exit, Execute WM (V/X/INPUT) "
read -r wm
	case $wm in
		[Vv]) printf "\n"
		ls -1 $wses;;
		[Xx]) ttyexit;;
		$wm) [ -f $wses/$wm.desktop ]
		case $? in
			0) runwm=$(sed -n 's/^Exec=//p' $wses/$wm.desktop)
			exec dbus-launch --exit-with-session $runwm;;
			*) printf "\nError: illegal input or .desktop file not found\n"
		esac
	esac
done
}

# Create function to directly start Xorg-based desktops
# First check if only one desktop file is found; if not, continue
# If sx is found, execute Xorg server via sx; otherwise, fall back to startx/xinit
# Afterwards, check for user input to search for xsessions .desktop files
# If nothing is found, report user error
xrun() {
printf "\nEntered X.Org prompt\n"
xcheck=$(ls "$xses" | wc -l)
case "$xcheck" in
	1) printf "\nOnly one environment found, running\n"
	runwm=$(sed -n 's/^Exec=//p' $xses/*.desktop)
	exec dbus-launch --exit-with-session $runwm;;
	0) printf "\n!!!CRITICAL ERROR!!!\n\nNo Xorg-based window manager or desktop environment found\nPress any key to go back to the start menu "
	read az
	sdmlogin
esac

while true; do
printf "\nWhat X.Org desktop environment do you want to enter?\n"
printf "The following options are available:\nView .desktop files, Exit, Execute WM (V/X/INPUT) "
read -r wm
	case $wm in
		[Vv]) printf "\n"
		ls -1 $xses;;
		[Xx]) ttyexit;;
		$wm) [ -f $xses/$wm.desktop ]
		case $? in
			0) runwm=$(sed -n 's/^Exec=//p' $xses/$wm.desktop)
			[ -f /usr/bin/sx ]
			case $? in
				0) exec dbus-launch --exit-with-session sx $runwm;;
				*) [ -f /usr/bin/startx ]
				case $? in
					0) exec dbus-launch --exit-with-session startx $runwm;;
					*) printf "\n!!!CRITICAL ERROR!!!\n\nXorg cannot be run, as startx and sx cannot be found\n"
				esac;;
			*) printf "\nError: illegal input or .desktop file not found\n";;
			esac
		esac
	esac
done
}

# Interactive console-based menu to navigate through all options presented in this script
sdmlogin() {
clear
printf "POSIX Shell Display Manager\n\n"
w
printf "\nRecent logins:\n\n"
last | head -n 6
printf "\nThe current shell in usage is $SHELL\n\n"
printf "The following X11 desktop environments are installed:\n\n"
ls -1 $xses
printf "\nThe following Wayland desktop environments are installed:\n\n"
ls -1 $wses
printf "\nNOTE: .desktop files from environments that cannot be found cannot be run.\n\n"

while true; do
printf "Do you want to run an X.Org or Wayland graphical server? (X/W/N) "
read -r xwn
	case $xwn in
		[Xx]) xrun;;
		[Ww]) wrun;;
		[Nn]) ttyexit;;
		*) printf "\nError: illegal input\n"
	esac
done
}

# Warning prompt
# If the script is executed outside of TTY1, warn the user
warning() {
while true; do
printf "WARNING: TTY1 was not detected.\nIt is not recommended to run a desktop environment outside of TTY1.\n"
printf "Do you want to continue? (Y/N) "
read -r yn
	case $yn in
		[Yy]) sdmlogin;;
		[Nn]) ttyexit;;
		*) printf "\nError: illegal input\n"
	esac
done
}

# Create parameter check at startup; default behavior hints to all usage paramaters
# Set variables, check if $DISPLAY is null and the environment is TTY1
# If neither conditions are met, enter warning prompt
concheck() {
case "${DISPLAY}" in
	"") case "${XDG_VTNR}" in
		1) return 0;;
		*) warning
	esac;;
	*) warning
esac
}

# Simple function to allow for direct calling of window managers and their respective servers
callwin() {
case $server in
	xorg) concheck
	runwm=$(sed -n 's/^Exec=//p' $xses/$wm.desktop)
	[ -f $xses/$wm.desktop ]
	case $? in
		0) exec dbus-launch --exit-with-session sx $runwm
	esac;;
	wayland) concheck
	runwm=$(sed -n 's/^Exec=//p' $wses/$wm.desktop)
	[ -f $wses/$wm.desktop ]
	case $? in
		0) exec dbus-launch --exit-with-session $runwm
	esac
esac
}

# Create variables and parameters for switch statement to handle of user input
# Call the conditional check function first and continue from there
xses=/usr/share/xsessions
wses=/usr/share/wayland-sessions
opt="-r, -h, -x, -w"

case $1 in
	-r|--run) concheck
	sdmlogin;;
	-h|--help) printf "Terminal-based display manager written in POSIX Shell\n"
	printf "Usage: posixsdm <option> [...]\nOptions:"
	printf "\n-r, --run\tRun the script and do a variable check"
	printf "\n-h, --help\tDisplay this help message"
	printf "\n-x, --xorg [INPUT] \tRun startx or sx directly (not recommended)"
	printf "\n-w, --wayland [INPUT]\tRun wayland-based environmet directly (not recommended)\n";;
	-x|--xorg) wm=$2
	server=xorg
	callwin;;
	-w|--wayland) wm=$2
	server=wayland
	callwin;;
	*) printf "Error: wrong or empty parameter\nUsage: posixsdm <option> [...]\nOptions: $opt\n"
esac
