#!/bin/sh

XDG_SESSION_TYPE=wayland

case $WM in
plasma)
	exec dbus-run-session /bin/startplasma-wayland;;
gnome)
	exec dbus-run-session /bin/gnome-shell --wayland;;
sway)
	exec dbus-run-session /bin/sway;;
esac
