#!/bin/sh
## posixsdm setup script

sdm_uninstall() {
	printf "Removing POSIXSDM and associated files...\n"
	[ -f /usr/bin/posixsdm ] && sudo rm /usr/bin/posixsdm
	[ -d "$HOME"/.config/posixsdm ] && rm -r "$HOME"/.config/posixsdm
	sed -i '/posixsdm/d' "$HOME"/.*profile
	printf "POSIXSDM has been removed.\n\n"

	while read -rp "The script has finished. Do you want to reboot the machine? ([Y]es/[N]o) " yn; do
		case "$yn" in
		[Yy]) reboot ;;
		[Nn])
			printf "\nExiting without rebooting, please restart your system.\n"
			exit 0
			;;
		*)
			printf "\nIncorrect input detected, repeating prompt\n"
			;;
		esac
	done
}

sdm_install() {
	while read -rp "Do you want to install POSIXSDM locally or globally? ([U]ser|RETURN/[R]oot) " priv; do
		case "$priv" in
		user | u | "")
			printf "Installing locally\n"
			dir="/.config/posixsdm/"
			mkdir "$HOME"/.config/posixsdm/
			chmod +x ./posixsdm
			cp ./posixsdm "$HOME"/.config/posixsdm/
			chmod +x "$HOME"/.config/posixsdm/
			break
			;;
		root | r)
			printf "\nInstalling globally\n"
			sudo cp ./posixsdm /usr/bin/
			sudo chmod +x /bin/posixsdm
			break
			;;
		*)
			printf "\nIncorrect input detected, repeating prompt\n"
			;;
		esac
	done

	while read -rp "Do you want to specify what DE/WM posixsdm runs on startup? ([Y]es/[N]o) " yn; do
		case "$yn" in
		[Yy])
			printf "\nCustom mode chosen \
			\nThe following DEs/WMs are available: \
			\n\nX.Org:\n"
			find /usr/share/xsessions -type f -printf "%f\n"
			printf "\nWayland:\n\n"
			find /usr/share/wayland-sessions -type f -printf "%f\n"
			while read -rp "Which desktop do you want to run?: " wm_input; do
				wm_full=$(find /usr/share/*sessions/$wm_input.desktop -type f -exec basename {} .desktop \;)
				runwm=$(grep -oP '(?<=Exec=).*' /usr/share/*sessions/"$wm_full".desktop | head -1)
				if [ -f /usr/bin/"$runwm" ]; then
					printf "exec %s%sposixsdm -w %s" "$HOME" "$dir" "$wm_full" >>"$conf"
					break 2
				else
					printf "Error: input is invalid or desktop doesn't exist\n"
				fi
			done
			;;
		[Nn])
			printf "Running posixsdm in standard mode\n"
			printf "exec %s%sposixsdm -r" "$HOME" "$dir" >>"$conf"
			break
			;;
		*)
			printf "Error: '%s' is not a valid option, repeating prompt\n\n" "$yn"
			;;
		esac
	done

	while read -rp "POSIXSDM has been installed. Do you want to reboot the machine? ([Y]es/[N]o) " yn; do
		case "$yn" in
		[Yy]) reboot ;;
		[Nn])
			printf "\nExiting without rebooting. \
			Please uninstall your current display manager and reboot your machine to run POSIXSDM.\n"
			exit 0
			;;
		*)
			printf "\nError: invalid input\n"
			;;
		esac
	done
}

sdm_setup() {
	while read -rp "Is your login shell ZSH, Bash or POSIX SH? ([Z]SH/[P]OSIXSH/E[x]it) " zpx; do
		case "$zpx" in
		[Zz])
			conf="$HOME/.zprofile"
			break
			;;
		[Pp])
			conf="$HOME/.profile"
			break
			;;
		[Xx])
			printf "Exiting.\n"
			exit 3
			;;
		*)
			printf "\nIncorrect input detected, repeating prompt...\n"
			;;
		esac
	done
	printf "\nInstalling via %s file.\n" "$conf"
	sdm_install
}

sdm_prompt() {
	while :; do
		printf "POSIXSDM Setup Script \
		\nPlease read the README file for more information before installation\n"
		read -rp "Do you want to install or uninstall POSIXSDM? ([I]nstall/[U]ninstall/E[x]it) " iux
		case "$iux" in
		[Ii])
			printf "\nStarting installation setup.\n"
			sdm_setup
			;;
		[Uu])
			printf "\nStarting uninstall setup.\n"
			sdm_uninstall
			;;
		[Xx])
			printf "Exiting.\n"
			return 3
			;;
		*)
			printf "\nIncorrect input detected, repeating prompt\n"
			;;
		esac
	done
}

case "$1" in
-i | --install) sdm_setup ;;
-is | --install-sh)
	printf "\nSelected BASH/POSIX Shell setup\n"
	conf="$HOME/.profile"
	;;
-iz | --install-zsh)
	printf "Selected ZSH setup\n"
	conf="$HOME/.zprofile"
	;;
-u | --uninstall) sdm_uninstall ;;
-h | --help) printf "POSIXSDM setup script \
	\nUsage: setup <option> [...]\n\nOptions:\n-i, --install\t\tRun the installer \
	\n-iz, --install-zsh\tInstall for ZSH Shell \
	\n-is, --install-sh\tInstall for BASH/POSIX Shell \
	\n-u, --uninstall\t\tRun the uninstaller \
	\n-h, --help\t\tDisplay this help message\n" ;;
"")
	printf "Type 'setup --help' to list all options\n"
	sdm_prompt
	;;
*)
	printf "Error: '%s' is not valid\nType './setup --help' for help\n" "$1"
	;;
esac

[ -n "$conf" ] && sdm_install
